apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mtg-mulligan-frontend
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
      - image: us-central1-docker.pkg.dev/PROJECT_ID/mtg-mulligan/frontend:latest
        ports:
        - name: http1
          containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: https://BACKEND_SERVICE_URL
        resources:
          limits:
            memory: 256Mi
            cpu: '1'
